#!/bin/bash

OUTPUT_DIR="output"
COPY_HOSTS="true"

if [ $# -eq 1 ] ; then
  OUTPUT_DIR=$1
elif [ $# -eq 2 ] ; then
  OUTPUT_DIR=$1
  COPY_HOSTS=$2
fi

REMOTE_DIR="/home/ubuntu/"
HOSTS="hosts"
IPMON_LOG="ipmon.log"
SYSMON_LOG="sysmon.log"
TEST_PERIOD_SEC=15

run_pssh() {
    local remote_cmd=$1
    local cmd="pssh -l ubuntu -h ${HOSTS} \"${remote_cmd}\""
    echo $cmd
    eval $cmd
}

run_cmd() {
    local cmd=$1
    echo $cmd
    eval $cmd
}


echo 'Start monitoring!'

if [ ${COPY_HOSTS} != "false" ] ; then
    run_cmd "pscp -l ubuntu -h ${HOSTS} ${HOSTS} ${REMOTE_DIR}"
else
    echo ''
    echo "Skipping hosts file copy"
fi
run_pssh "sudo ${REMOTE_DIR}ipmon ${REMOTE_DIR}hosts >& ${REMOTE_DIR}${IPMON_LOG} &"
run_pssh "sudo ${REMOTE_DIR}sysmon 0 ${REMOTE_DIR}${SYSMON_LOG} 0x48040020 10000 2 > /dev/null &"

echo ''
echo 'Monitoring in progress...'
sleep ${TEST_PERIOD_SEC}

run_pssh "sudo pkill --signal 2 ipmon"
run_pssh "sudo pkill --signal 2 sysmon"
echo ''
echo 'Done testing! Collecting data...'

if [ ! -d "${OUTPUT_DIR}" ]; then
    mkdir -p ${OUTPUT_DIR}
else
    rm -rf ${OUTPUT_DIR}/*
fi

run_cmd "pslurp -l ubuntu -h ${HOSTS} -L ${OUTPUT_DIR} ${REMOTE_DIR}${IPMON_LOG} ."
run_cmd "pslurp -l ubuntu -h ${HOSTS} -L ${OUTPUT_DIR} ${REMOTE_DIR}${SYSMON_LOG} ."

echo ''
echo 'Done monitoring!'


